export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const LOAD_USER = "LOAD_USER";
export const LOAD_USER_FAILS = "LOAD_USER_FAILS";

export const SOCKET_CONNECT = "SOCKET_CONNECT";
export const SOCKET_CONNECT_FAIL = "SOCKET_CONNECT_FAIL";

export const PC_CONNECTION_STATE = "PC_CONNECTION_STATE";
