export const CHECK_MATCHED = "CHECK_MATCHED";
export const GET_KEY = "GET_KEY";

export const REFRESH_INFO = "REFRESH_INFO";
export const GET_CURRENT_ORDERS = "GET_CURRENT_ORDERS";
export const RESET_CURRENT_ORDERS = "RESET_CURRENT_ORDERS";


export const UPDATE_STATUS = "UPDATE_STATUS";
export const GET_PAST_REQUESTS = "GET_PAST_REQUESTS";


export const GET_LAST_POWER = "GET_LAST_POWER";
export const GET_LAST_LOCK = "GET_LAST_LOCK";
export const GET_RANSOM_LOCK_STATE = "GET_RANSOM_LOCK_STATE";

export const GET_PAST_REQUEST_FOR_EVERY_CONTROL = "GET_PAST_REQUEST_FOR_EVERY_CONTROL";



export const RESET_PAST_STATE = "RESET_PAST_STATE";


export const GET_PAST_SCREENSHOTS = "GET_PAST_SCREENSHOTS";


export const SET_DOWNLOAD_RATE = "SET_DOWNLOAD_RATE";

