export const CHECK_MATCHED = "CHECK_MATCHED";
export const GET_KEY = "GET_KEY";

export const REFRESH_INFO = "REFRESH_INFO";
export const GET_CURRENT_ORDERS = "GET_CURRENT_ORDERS";
export const RESET_CURRENT_ORDERS = "RESET_CURRENT_ORDERS";


export const UPDATE_STATUS = "UPDATE_STATUS";
export const GET_PAST_REQUESTS = "GET_PAST_REQUESTS";

